### ISSUE TITLE
[BUG] "No authorization header provided" error on public upload setup

### ISSUE THREAD

**Issue by ivancarlosti** [chibisafe/chibisafe#705]
**Describe the bug**
When open the website to upload files using not logged account, I get the message "No authorization header provided".
This error do not happens when I disable Public Mode.

**To Reproduce**
1. Enable Public Mode
2. Open the site font page
3. See error

**Expected behavior**
A front page without error

**Screenshots**
![image](https://github.com/user-attachments/assets/d7a6efe9-c494-4f9e-a779-bc54ff4c5ef2)

**Additional context**
Uploads works fine, the only problem is the error popping up on front page. I use nginx on host (not docked) as reverse proxy for docker websites. I already tried to redirect nginx to Caddy with same issue, now I am connecting directly to chibisafe (host:8001) and /api, /docs (host:8000)

My docker compose file:

```
name: envio

services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    container_name: envio
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    ports:
      - 8001:8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    container_name: envio-server
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
```

My nginx setup:

```
server {
  listen 80;
  listen [::]:80;
  listen 443 quic;
  listen 443 ssl;
  listen [::]:443 quic;
  listen [::]:443 ssl;
  http2 on;
  http3 on;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name <host>;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$request_uri permanent;
  }

###################
  location /api {
    proxy_pass http://127.0.0.1:8000;
  }

  location /docs {
    proxy_pass http://127.0.0.1:8000;
  }
###################

  location @reverse_proxy {
    proxy_pass {{reverse_proxy_url}};
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass_request_headers on;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout 900;
    proxy_send_timeout 900;
    proxy_read_timeout 900;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;
  }

  {{settings}}

  include /etc/nginx/global_settings;

  add_header Cache-Control no-transform;

  index index.html;

  location ^~ /.well-known {
    auth_basic off;
    allow all;
    try_files $uri @reverse_proxy;
  }

  location / {
    try_files $uri @reverse_proxy;
  }
}
```

**Comment by kobayashi90** [comment]
good to know i am not the only person having this problem.

**Comment by Pitu** [comment]
This is already fixed in the new version that's coming up soon.
I'll close this issue as soon as we release.

**Comment by ivancarlosti** [comment]
Hi @Pitu , regarding your last message, this fix is aleady published on it will be released on a major version? Because the issue persists here in version published today

Thanks

**Comment by Pitu** [comment]
It's not yet published, it should come with the next major version

**Comment by kobayashi90** [comment]
> It's not yet published, it should come with the next major version

I know you might have better things to do but making more regular updates would be actually great.
Focus on smaller issues so your huge amount of unfinished issues are slowly decreasing, or alternatively get people that help you on deciding these changes. It really helps.

**Comment by Pitu** [comment]
Thanks for your comment.
In an ideal world where life doesn't get in the middle that would work, and it usually does.
But there's a major version that is being worked on for many months now, but unfortunately, we can't find the time to polish it and release it.

Hopefully soon.

**Comment by kobayashi90** [comment]
> Thanks for your comment. In an ideal world where life doesn't get in the middle that would work, and it usually does. But there's a major version that is being worked on for many months now, but unfortunately, we can't find the time to polish it and release it.
> 
> Hopefully soon.

Yet you ignored the Part where ive said that you should Grab 3-4 from the Contributers and let them handle this so you have less to think about it. A little work of your Shoulders.
Just saying, i actually think a lot of People would agree with me on this.
You're not alone in this.

**Comment by ivancarlosti** [comment]
My installation was targeted, I blocked anonymous upload and avoid "No authorization header provided" issue, but signup was also targeted. I will suspend using it awhile until we have a proper signup form with e-mail and confirmation 😭

**Comment by Pitu** [comment]
I don't understand what you mean. 
Targeted? If you don't want people to sign up set your instance to private.

**Comment by ivancarlosti** [comment]
> I don't understand what you mean. Targeted? If you don't want people to sign up set your instance to private.

I was expecting some users but with some control to not have the service abused, without any control anyone can create random user and upload files without even validate an email address

**Comment by kobayashi90** [comment]
still not fixed even on the latest one, sigh i give up..

**Comment by Pitu** [comment]
The latest push wasn't meant to fix that issue, as I haven't had the time to look into that one yet

**Comment by Pitu** [comment]
Fixed in #729
